// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PomorzeNadw_vJan.Data;

#nullable disable

namespace pomorzenadw_vmay.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PomorzeNadw_vJan.Models.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<string>("Duration")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Name")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Phonenum")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Subtype")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Type")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Voivodeship")
                        .HasColumnType("VARCHAR(99)");

                    b.Property<string>("Weblink")
                        .HasColumnType("ntext");

                    b.Property<int>("imageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });
#pragma warning restore 612, 618
        }
    }
}
